### ISSUE TITLE
AI Crashing

### ISSUE THREAD

**Issue by Gideon9212** [Gideon9212/windbot#1]
AI will crash about once a hour or 2. I was able to get at least 2 errors from the crashing

> {"name":"mycard","hostname":"Gideon-PC","pid":20672,"level":40,"msg":"WindBot Er
ror: \n","time":"2017-09-22T04:45:20.222Z","v":0}
{"name":"mycard","hostname":"Gideon-PC","pid":20672,"level":40,"msg":"WindBot Er
ror: Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of r
ange. Must be non-negative and less than the size of the collection.\r\nParamete
r name: index\r\n   at System.ThrowHelper.ThrowArgumentOutOfRangeException(Excep
tionArgument argument, ExceptionResource resource)\r\n   at System.Collections.G
eneric.List`1.get_Item(Int32 index)\r\n   at WindBot.Game.GameAI.OnSelectCard(IL
ist`1 cards, Int32 min, Int32 max, Boolean cancelable)\r\n   at WindBot.Game.Gam
eBehavior.InternalOnSelectUnselectCard(BinaryReader packet, Func`5 func)\r\n   a
t WindBot.Game.GameBehavior.OnSelectUnselectCard(BinaryReader packet)\r\n   at W
indBot.Game.GameBehavior.OnPacket(BinaryReader packet)\r\n   at WindBot.Game.Gam
eClient.OnPacketReceived(BinaryReader reader)\r\n   at YGOSharp.Network.BinaryCl
ient.ReceivePendingPackets()\r\n   at YGOSharp.Network.BinaryClient.Update()\r\n
   at WindBot.Game.GameClient.Tick()\r\n   at WindBot.Program.Run(Object o)\r\n
  at System.Threading.ThreadHelper.ThreadStart_Context(Object state)\r\n   at Sy
stem.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.
Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallbac
k callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.Exe
cutionContext.Run(ExecutionContext executionContext, ContextCallback callback, O
bject state)\r\n   at System.Threading.ThreadHelper.ThreadStart(Object obj)\n","
time":"2017-09-22T04:45:20.223Z","v":0}

> {"name":"mycard","hostname":"Gideon-PC","pid":39952,"level":40,"msg":"WindBot Er
ror: Unhandled Exception: System.NullReferenceException: Object reference not se
t to an instance of an object.\r\n   at WindBot.Game.GameBehavior.OnJoinGame(Bin
aryReader packet)\r\n   at WindBot.Game.GameBehavior.OnPacket(BinaryReader packe
t)\r\n   at WindBot.Game.GameClient.OnPacketReceived(BinaryReader reader)\r\n
at YGOSharp.Network.BinaryClient.ReceivePendingPackets()\r\n   at YGOSharp.Netwo
rk.BinaryClient.Update()\r\n   at WindBot.Game.GameClient.Tick()\r\n   at WindBo
t.Program.Run(Object o)\r\n   at System.Threading.ThreadHelper.ThreadStart_Conte
xt(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(Executio
nContext executionContext, ContextCallback callback, Object state, Boolean prese
rveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext exec
utionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r
\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext,
 ContextCallback callback, Object state)\r\n   at System.Threading.ThreadHelper.
ThreadStart(Object obj)\n","time":"2017-10-19T09:42:56.337Z","v":0}

The first error is a bit old and haven't seen a while. Has to do mainly with

> GameBehavior.OnSelectUnselectCard

While the 2nd is new and keeps popping up a lot more often. 

> System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at WindBot.Game.GameBehavior.OnJoinGame

Both annoying, both somewhere in the gamebehavior.cs
https://github.com/Gideon9212/windbot/blob/master/Game/GameBehavior.cs

And still unable to figure out a exact fix. 
Node version: 8.7.0

**Comment by AndreOliveiraMendes** [comment]
idk if that help ~maybe not~ but i organized the message so it more easy to see it?
ps: aparenty it referencing a null object and indexing out of range, but idk why.

> {"name":"mycard","hostname":"Gideon-PC","pid":20672,"level":40,"msg":"WindBot Error:
> ","time":"2017-09-22T04:45:20.222Z","v":0}
> {"name":"mycard","hostname":"Gideon-PC","pid":20672,"level":40,"msg":"WindBot Error: Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
> at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
> at System.Collections.Generic.List1.get_Item(Int32 index)
> at WindBot.Game.GameAI.OnSelectCard(IL ist1 cards, Int32 min, Int32 max, Boolean cancelable)
> at WindBot.Game.GameBehavior.InternalOnSelectUnselectCard(BinaryReader packet, Func`5 func)
> at WindBot.Game.GameBehavior.OnSelectUnselectCard(BinaryReader packet)
> at WindBot.Game.GameBehavior.OnPacket(BinaryReader packet)
> at WindBot.Game.GameClient.OnPacketReceived(BinaryReader reader)
> at YGOSharp.Network.BinaryClient.ReceivePendingPackets()
> at YGOSharp.Network.BinaryClient.Update()
> at WindBot.Game.GameClient.Tick()
> at WindBot.Program.Run(Object o)
> at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> at System.Threading.ThreadHelper.ThreadStart(Object obj)
> ","time":"2017-09-22T04:45:20.223Z","v":0}
> 
> {"name":"mycard","hostname":"Gideon-PC","pid":39952,"level":40,"msg":"WindBot Error: Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
> at WindBot.Game.GameBehavior.OnJoinGame(BinaryReader packet)
> at WindBot.Game.GameBehavior.OnPacket(BinaryReader packet)
> at WindBot.Game.GameClient.OnPacketReceived(BinaryReader reader)
> at YGOSharp.Network.BinaryClient.ReceivePendingPackets()
> at YGOSharp.Network.BinaryClient.Update()
> at WindBot.Game.GameClient.Tick()
> at WindBot.Program.Run(Object o)
> at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext,ContextCallback callback, Object state)
> at System.Threading.ThreadHelper.ThreadStart(Object obj)
> ","time":"2017-10-19T09:42:56.337Z","v":0}

**Comment by AndreOliveiraMendes** [comment]
hum, i think investigating

>         public IList<ClientCard> OnSelectCard(IList<ClientCard> cards, int min, int max, bool cancelable)
>         {
>             // Check for the executor.
>             IList<ClientCard> result = Executor.OnSelectCard(cards, min, max, cancelable);
>             if (result != null)
>                 return result;
> 
>             // Update the next selector.
>             CardSelector selector = GetSelectedCards();
> 
>             // If we selected a card, use this card.
>             if (selector != null)
>                 return selector.Select(cards, min, max);
> 
>             // Always select the first available cards and choose the minimum.
>             IList<ClientCard> selected = new List<ClientCard>();
> 
>             for (int i = 0; i < min; ++i)
>                 selected.Add(cards[i]);
> 
>             return selected;
>         }
> 

more precise

https://github.com/Gideon9212/windbot/blob/master/Game/GameAI.cs#L176

i guess something not passing right min variable, so it geting out of index, so it would be good to investigate that.

**Comment by Gideon9212** [comment]
Issue most likely lies in edo's last commit.
https://github.com/edo9300/windbot/commit/d8551317ed4fa11ab4549a5675edcf519a24c24c

**Comment by Gideon9212** [comment]
Bad news

> {"name":"mycard","hostname":"Gideon-PC","pid":12604,"level":40,"msg":"WindBot Er
ror: Unhandled Exception: System.NullReferenceException: Object reference not se
t to an instance of an object.\r\n   at WindBot.Game.GameBehavior.OnJoinGame(Bin
aryReader packet)\r\n   at WindBot.Game.GameBehavior.OnPacket(BinaryReader packe
t)\r\n   at WindBot.Game.GameClient.OnPacketReceived(BinaryReader reader)\r\n
at YGOSharp.Network.BinaryClient.ReceivePendingPackets()\r\n   at YGOSharp.Netwo
rk.BinaryClient.Update()\r\n   at WindBot.Game.GameClient.Tick()\r\n   at WindBo
t.Program.Run(Object o)\r\n   at System.Threading.ThreadHelper.ThreadStart_Conte
xt(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(Executio
nContext executionContext, ContextCallback callback, Object state, Boolean prese
rveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext exec
utionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r
\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext,
 ContextCallback callback, Object state)\r\n   at System.Threading.ThreadHelper.
ThreadStart(Object obj)\n","time":"2017-10-24T03:01:34.005Z","v":0}

Pops up on the main repo as well (Tested with unmodifyed MR3 server): https://github.com/moecube/windbot
We back at square one on the 2nd error. First error still most likely edos last commit.

**Comment by mercury233** [comment]
I guess I found the reason for that `NullReferenceException` in `OnJoinGame`

The deck name in `bots.json` is incorrect, and the bot will use random deck when it can't find the deck

And finally it picked AI_Test, but this AI deck don't have a ydk. So the `Deck` in 
https://github.com/Gideon9212/windbot/blob/926b67874f97e275033c3770126d7f0ac691bc93/Game/GameBehavior.cs#L130-L131
become null

To fix this, change the deck name in `bots.json`, make them are same as the names in executor code.

**Comment by Gideon9212** [comment]
Fixed the deck names.
https://github.com/Gideon9212/windbot/commit/f7e28aa4b19153485592f1fd7a43515cde55ce79

Apparently Toadally Awesome and Zexal Weapons needed a space. >,<

**Comment by Gideon9212** [comment]
Applied a quick fix 
https://github.com/Gideon9212/windbot/commit/b0e45b67bed370c1b306895eef9a487b44762b4d
And haven't seen the 1st error yet.
2nd error is still happening even after bots.json change. :disappointed: 
`WindBot Error: Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at WindBot.Game.GameBehavior.OnJoinGame(BinaryReader packet)    
at WindBot.Game.GameBehavior.OnPacket(BinaryReader packet)    
at WindBot.Game.GameClient.OnPacketReceived(BinaryReader reader)  
at YGOSharp.Network.BinaryClient.ReceivePendingPackets()    
at YGOSharp.Network.BinaryClient.Update()    
at WindBot.Game.GameClient.Tick()
at WindBot.Program.Run(Object o)   
at System.Threading.ThreadHelper.ThreadStart_Conte xt(Object state)    
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)    
at System.Threading.ThreadHelper. ThreadStart(Object obj)`

**Comment by Gideon9212** [comment]
Made a change to see if that one extra exect caused the issue.
https://github.com/Gideon9212/windbot/commit/3a61d134d272e5f89b702106d946548b95d1b050
Lets hope that fix's the error.

**Comment by Gideon9212** [comment]
`WindBot Error: Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at WindBot.Game.GameBehavior.OnJoinGame(BinaryReader packet)
   at WindBot.Game.GameBehavior.OnPacket(BinaryReader packet)
   at WindBot.Game.GameClient.OnPacketReceived(BinaryReader reader)
   at YGOSharp.Network.BinaryClient.ReceivePendingPackets()
   at YGOSharp.Network.BinaryClient.Update()
   at WindBot.Game.GameClient.Tick()
   at WindBot.Program.Run(Object o)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)`

Damn it. The change above did nothing to fix the error.

**Comment by Gideon9212** [comment]
Added a bot to record errors on the server (idea and design by edo)
So far everytime the AI crashes with the above error, theres a script error that follows it. 
Is windbot reading a script error as a null, causing it to crash? @mercury233

**Comment by mercury233** [comment]
what script error?

**Comment by Gideon9212** [comment]
Any. The last one I had was 
`Debug: [string "./expansions/script/c99111753.lua"]:29: attempt to index a nil value (global 'c')`

And the one before that is

`Debug: [string "./expansions/script/c40509732.lua"]:21: Parameter 2 should be "Function".`

We fixed them both but it still crashes. I'm just wondering though is how the AI reads a script? Maybe its looping on a script or something.

**Comment by mercury233** [comment]
The AI don't read scripts at all. The problem still happens at `GameBehavior.OnJoinGame`

**Comment by Gideon9212** [comment]
Damn. The bot.json is correct, the extra stuff was removed, so why is it still having issues at OnJoinGame...

Also apparently at some point the AI will use different AI deck then it was meant to....
